# Generated by Django 3.2 on 2022-04-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220403_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_upload']},
        ),
        migrations.AddField(
            model_name='author',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
